# permissions for end users to edit ipconfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/managed-by: kustomize
  name: ipconf-editor-role
rules:
- apiGroups:
  - dynamicconfigip.github.com
  resources:
  - ipconfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamicconfigip.github.com
  resources:
  - ipconfs/status
  verbs:
  - get
