---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dynamicconfigip.github.com
  resources:
  - ipconfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamicconfigip.github.com
  resources:
  - ipconfs/finalizers
  verbs:
  - update
- apiGroups:
  - dynamicconfigip.github.com
  resources:
  - ipconfs/status
  verbs:
  - get
  - patch
  - update
