# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM local_ubuntu:1.1
ADD bin/cli  /usr/local/bin
#RUN apt update; \
#    apt install -y iputils-ping net-tools tcpdump curl
# Create a non-root user with UID and GID 65532
#RUN useradd -u 65532 -r -s /bin/false nonrootuser
USER 65532:65532
ENTRYPOINT ["sleep 36000"]
