apiVersion: dynamicconfigip.github.com/betav1
kind: Ipconf
metadata:
  name: ipconf
  namespace: default
spec:
  type: bridge
  owner: mynginx-nginx-chart-1
  cniVersion: 0.3.1
  trust: "on"
  ipItems:
    - iface: eth0
      ipaddress: 192.168.1.10
      netmask: "24"
      type: static
    - iface: eth1
      ipaddress: 192.168.2.10
      netmask: "24"
      type: static
