apiVersion: dynamicconfigip.github.com/betav1
kind: Ipconf
metadata:
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/managed-by: kustomize
  name: ipconf-liu
spec:
  owner: "nginx-0"
  iface: eth0
  ipaddress: "10.10.10.10"
  netmask: "255.255.25.0"
  # TODO(user): Add fields here
