apiVersion: dynamicconfigip.github.com/betav1
kind: Ipconf
metadata:
  name: ipconf
  namespace: default
spec:
  owner: test-nginx-chart-1
  cniVersion: 0.3.1
  ipItems:
    - iface: eth0
      ipaddress: 192.168.1.10
      netmask: "24"
    - iface: eth0
      ipaddress: 192.168.2.10
      netmask: "24"
