apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: my-network
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br0",
    "isGateway": true,
    "ipam": {
      "type": "host-local",
      "subnet": "10.10.0.0/16",
      "rangeStart": "10.10.0.200",
      "rangeEnd": "10.10.0.216",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "10.10.0.1"
    }
  }'